POST http://localhost:8000/generate
Content-Type: application/json

{
    "questions": [
        "豊臣 秀吉 が 造営 し た 聚楽 第 の 一部 を 移築 し た もの で ある 京都 の 西 本願 寺 に ある 国宝 の 建物 と いえ ば 何 でしょう ?",
        "愛称 を チータ と いう 『 いっぽん どっこ の 唄 』 『 三百 六十 五 歩 の マーチ 』 など の ヒット 曲 で 知ら れる 歌手 は 誰 でしょう ?",
        "『 地獄 門 』 や 『 カレー の 市民 』 そして 『 考える 人 』 など の 作品 で 知ら れる フランス の 彫刻 家 は 誰 でしょう ?"
    ]
}