POST http://localhost:8000/generate
Content-Type: application/json

{
    "questions": [
        "競馬で1枠の騎手の帽子の色は白ですが、2枠の騎手の帽子の色は何でしょう?",
        "L字型、キャッシング型、マレット型などの種類がある、ゴルフで特にグリーン周りで使うクラブを何というでしょう?",
        "三角形の二辺の中点を結んだ線分は、残りの一辺と平行かつ残りの辺の長さの半分の長さになることを何というでしょう?",
        "「ここに地終わり、海始まる」と書かれた石碑でもおなじみの、ポルトガルにあるヨーロッパ最西端の岬とは何岬でしょう?"
    ]
}

# "豊臣 秀吉 が 造営 し た 聚楽 第 の 一部 を 移築 し た もの で ある 京都 の 西 本願 寺 に ある 国宝 の 建物 と いえ ば 何 でしょう ?", 
# "愛称 を チータ と いう 『 いっぽん どっこ の 唄 』 『 三百 六十 五 歩 の マーチ 』 など の ヒット 曲 で 知ら れる 歌手 は 誰 でしょう ?", 
# "『 地獄 門 』 や 『 カレー の 市民 』 そして 『 考える 人 』 など の 作品 で 知ら れる フランス の 彫刻 家 は 誰 でしょう ?"

#         "思いがけ ない 突発 的 な 事柄 を いう 「 青天 の 霹靂 」 、 さて この 「 霹靂 」 と は どんな 自然 現象 の こと でしょう ?",
#         "匈奴 に 捕われ た 将軍 ・ 李陵 を 弁護 し た ため に 罰せ られ 、 宦官 と なっ た 、 「 史記 」 の 作者 と し て 知ら れる 人物 は 誰 でしょう ?",
#         "日韓 ワールド カップ で は ブラジル 代表 の キャプテン を 務め た 、 7 月 から J リーグ ・ 横浜 F マリノス で プレー する サッカー 選手 は 誰 でしょう ?",
#         "その 名 は 現在 の インドネシア から 日本 に 伝わっ て き た こと に ちなむ 、 メーク イン ・ 男爵 など の 種類 が ある 芋 と いえ ば 何 でしょう ?"

